name: Deploy to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'small-cap-screener'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

    - name: Configure Azure Web App
      uses: azure/appservice-settings@v1
      with:
        app-name: 'small-cap-screener'
        app-settings-json: |
          [
            {
              "name": "SCM_DO_BUILD_DURING_DEPLOYMENT",
              "value": "true"
            },
            {
              "name": "STREAMLIT_SERVER_PORT",
              "value": "8000"
            },
            {
              "name": "STREAMLIT_SERVER_ADDRESS",
              "value": "0.0.0.0"
            }
          ]
        general-settings-json: |
          {
            "linuxFxVersion": "PYTHON|3.11"
          }
